[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[programs.localnet]
nodefi_vault = "F14yVkHb8S1ByEStSshM1Bep6DkFpdA9yiUkgNcs9r1V"

[provider]
cluster = "localnet"
wallet  = "~/.config/solana/id.json"
